 <input
     {{
      $attributes->class([
        'border-stroke 
         dark:border-dark-3 
         dark:text-dark-6 
         dark:bg-dark 
         text-body-color 
         focus:border-primary 
         w-full 
         rounded 
         border 
         py-3 
         px-[14px] 
         text-base 
         outline-none',
     ])
    }}
/>
